### PR TITLE
Database seed

### LINKED ISSUE #128: build up seed database file

### PR DESCRIPTION
**Pull request by AndrewSouthpaw**
Closes #128 .

### CODE REVIEW

**Comment by AndrewSouthpaw** [comment]
it's failing right now because I now write the tests to use `username` instead of `user_id`, which will then work after they all get integrated

**Comment by ruben1** [comment]
it might be failing because the user_id is required when creating a screenshot

**Comment by ruben1** [comment]
yep, i think it's right

**Comment by AndrewSouthpaw** [comment]
rebased and merging

**Pull request merged**
