### PR TITLE
remove promise handling

### PR DESCRIPTION
**Pull request by ruben1**
client does get request to the right API endpoint and gets the right data but the data is not set to the variable that displays the data in the view.
I'm removing the promise because most likely that's the problem. Any thoughts?

### CODE REVIEW

**Comment by ruben1** [comment]
Also, the promise is handled in both service and controller so that might be the problem

**Comment by AndrewSouthpaw** [comment]
I'm not so sure about this one. In Scott Moss's solution, he handles the promise in the service and the controller. And that one definitely works. Are you sure the issue is the promise?

**Comment by ruben1** [comment]
right, it might not be that

**Comment by ruben1** [comment]
i'll look more into it

**Comment by ruben1** [comment]
Ok, i have implemented it the way Scott did it in the angular solution

**Pull request closed without merging**
